import { ReactNode } from 'react';
import { SessionProvider } from 'next-auth/react';
import { ThemeProvider } from "@/app/ThemeProvider";
import "./globals.css";
import { auth } from "@/auth";

interface RootLayoutProps {
  children: ReactNode;
}

export const metadata = {
  title: 'Redux App',
  description: 'Generated by M.A. Rahman',
};

export default async function RootLayout({ children }: RootLayoutProps) {

  const session = await auth();
  return (
    <html lang="en">
      <head>
        {/* Include any necessary head elements here */}
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="stylesheet" href="/path/to/your/globals.css" />
      </head>
      <body>
        <SessionProvider session={session}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* Ensure you pass the session prop if necessary */}
            {children}
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import { ThemeProvider } from "@/app/ThemeProvider";
// import { SessionProvider } from "next-auth/react";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Medhakunja Academy",
//   description: "Generated by Medhakunja Academy",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <SessionProvider >
//       <html lang="en">
// <body suppressHydrationWarning={true}>
// <ThemeProvider
//   attribute="class"
//   defaultTheme="system"
//   enableSystem
//   disableTransitionOnChange
// >
//     {children}
//   </ThemeProvider>
// </body>
//       </html>
//     </SessionProvider>
//   );
// }




// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import { ThemeProvider } from "@/app/ThemeProvider"
// import { SessionProvider } from "next-auth/react";
// import { auth } from "@/auth";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Medhakunja Academy",
//   description: "Generated by Medhakunja Academy",
// };

// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {

//   const session = await auth();

//   return (
//     <SessionProvider session={session}>
//       <html lang="en">
//         <body suppressHydrationWarning={true}>
//           <ThemeProvider
//             attribute="class"
//             defaultTheme="system"
//             enableSystem
//             disableTransitionOnChange
//           >
//             {children}
//           </ThemeProvider>
//         </body>
//         {/* <body className={inter.className}>{children}</body> */}
//       </html>
//     </SessionProvider>

//   );
// }
